### ISSUE TITLE
Dev Task #8 - Create Database models from ERD

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#1]
As a **developer**, I can **set up my models.py files** so that I can **create my database tables**

### Acceptance Criteria:

1.  Successfully create TennisBudies ERD.
2.  Create apps for each model and add models to models.py
3.  Import revelavant Django/Cloudinary models.

### Tasks:

- [x] Import relevant Django/Cloudinary Models
- [x] Add user/buddy model + add to INSTALLED_APPS + Migrate the changes to the db
- [x] Add booking model + add to INSTALLED_APPS + Migrate the changes to the db
- [x] Add event model + add to INSTALLED_APPS + Migrate the changes to the db
- [x] Add court model + add to INSTALLED_APPS + Migrate the changes to the db
- [x] #9
