### ISSUE TITLE
User Story #1 Homepage Setup

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#10]
As a **user**, I would like to **view the apps homepage** so that I can **learn about the app and see what services it provides**.

### Acceptance Criteria
1.  The user can learn about the websites mission/services from the home page.
2.  The user can browse the home page without having to be registered and logged in.

### Tasks
- [x] Create a base temple and extend it in home view template
- [x] Create index.html template for Home page with basic skeleton
- [x] Update urls.py
- [x] Add bootstrap navbar
- [x] Add bootstrap footer
