### ISSUE TITLE
User Story #2 - Navigation

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#11]
As a **user** I can **locate the navigation area** so that I can **easily access different parts of the website**

### Acceptance Criteria
1.  The header is clearly distiguishable at the top of the page.
2.  The header sticks to the top of the page at all times.
3.  All icons take the user to the relevant page.

### Tasks
- [x] Add Tennis Buddies logo in minified size to the NavBar
- [x] Create relevant pages
- [x] Add links to NavBar items
- [x] Connect urls
