### ISSUE TITLE
User Story #3 - Footer

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#12]
As a **user**, I can **access relevant information about opening hours, contact information and social media links without having to scroll back to the top of the page** so that I can **visit the club, contact the club and follow the club online**.

### Acceptance Criteria
1. Footer is consistent through all the pages
2. Footer sticks to the bottom of the page
3. Footer contains relevant information (club opening hours, links to pages, links to interesting resources, contact infromation and social media links)
4. All links, including social media open in a new tab.

### Tasks
- [x] Update links to interesting sources in the footer
- [x] Update links to site navigation
- [x] Add opening hours
- [x] Add contact information
