### ISSUE TITLE
User Story #4 - Sign up

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#13]
As an **unregistered user** I want to be able **to sign up onto the website** so that I can **access websites functionality and content**

### Acceptance Criteria
1.  When I click on Sign Up button, I'm redirected to a sign uo form

### Tasks
- [x] Update links in NavBar in header.html template
- [x] Update signup.html template in templates/allauth
- [x] Style the form using crispy filter
