### ISSUE TITLE
User Story #5 - Log in

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#14]
As a **registered user** I want to be able **to sign in into my account** so that I can **get access to the website's functionality and options**

### Acceptance Criteria
1.  When I click on Sign in button, a sign in form is displayed
2. I can enter my email and password to sign in
3. I can choose to remember my sign in information

### Tasks
- [x] Update links in NavBar in header.html template
- [x] Update login.html template in templates/allauth
- [x] Style the form using crispy filter
