### ISSUE TITLE
User Story #6 - Log out

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#15]
As a **signed in user** I want to be able **to sign out of my account** so that I can **keep my account private and safe**

### Acceptance Criteria
1.  When I click on Sign Out button, I'm redirected to a sign out form
2. I want to be able to confirm my decision to sign out
3. When I am signed out, I want to see the login option

### Tasks
- [x] Update links in NavBar in header.html template
- [x] Update signout.html template in templates/allauth
- [x] Style the form using crispy filter
