### ISSUE TITLE
Dev task # Install django_crispy forms

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#16]
As a **developer** I want to be able **create appealing forms** so that the user **is pleased and wants to stay on the website**

### Acceptance Criteria
1. It is possible to style the django signup, login and logout forms.

### Tasks
- [x] Install django_crispy
- [x] Update the settings file (add crispy app, templates)
- [x] Add  {% load crispy_forms_tags %}  on top of each file - not necessary
- [x] #17

**Comment by lucia2007** [comment]
I had copied the allauth templates into templates/allauth/templates instead of templates/allauth, so the crispy filter and other changes could not be applied.
