### ISSUE TITLE
User Story #4Set Up User_profile

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#19]
As a **user** I can **enter my personal details** so that I can **create an account with Tennis buddies and be contacted in case of need**

### Acceptance Criteria
1.  User is taken to an appealing page where they can easily enter all required information.
2.  Created user_profile page saves successfully into the database.
3.  User with a completed user_profile can create a buddy profile which is needed when looking for a tennis buddy.

### Tasks

- [x] Create User Profile set-up page
- [x] Create form for the user to fill in
- [x] #20
- [x] Add url path to urls.py
