### ISSUE TITLE
User Story #5 Set Up Buddy Profile

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#21]
As a **signed in user with an active profile** I can **create a buddy profile** so that **I can use the search functionality to find the best tennis partner**

### Acceptance Criteria
1.  User can fill in a simple form, add a profile picture and indicate their preferences for type of play, skill level, availability etc.
2.  Created buddy profile is successfully saved into the database.
3.  User with a complete buddy profile can avail of the search functionality (this will constitute a separate user story later on).

### Tasks
- [x]  Create Buddy profile set-up page
- [x]  Create form for the user to fill in
- [x] #22
- [x]  Add url path to urls.py

**Comment by lucia2007** [comment]
I had a similar problem with saving the form as in issue #20. Both issues got solved with the same fix.

**Comment by lucia2007** [comment]
To prefill the email in the AddBuddy form: 
def get_initial(self):
        initial = super().get_initial()
        initial['email'] = self.request.user.email
        return initial
