### ISSUE TITLE
User Story #9 Edit User Profile

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#23]
As a **user**, I can **edit my user profile** to **update my personal details**.

### Acceptance Criteria
1.  User is taken to Contact Info Form when 'Edit' button is clicked
2.  User can see the prefilled fields with his original information which can be edited
3.  The placeholder text disappears when user starts editing
4.  New details are saved in the database

### Tasks
- [x] Edit button takes the user to the Contact Info edit page
- [x] Form with editable fields is displayed
- [x] 'Edit Your Contact Details' button pushes the changes in the database
