### ISSUE TITLE
User Story #11 Edit Buddy Profile

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#24]
As a **user**, I can **edit my buddy profile** to **update my preferences regarding the style of play/practice**.

### Acceptance Criteria
1.  User is taken to Profile Form when 'Edit' button is clicked
2.  User can see the prefilled fields with his original information which can be edited
3.  The placeholder text disappears when user starts editing
4.  New details are saved in the database

### Tasks
- [x] Edit button takes the user to the user profile edit page
- [x] Form with editable fields is displayed
- [x] 'Edit Your Profile' button pushes the changes in the database

**Comment by lucia2007** [comment]
When I want to edit the form, there is currently no information about the current image. I can see it in the admin panel, but not in the edit form. Report as bug.
