### ISSUE TITLE
User Story #12 Delete Buddy Profile

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#25]
As a ** registered user** I can **press delete button on my buddy profile form** so that I can **delete all provided information regarding my preferences for a tennis partner, including pictures**

### Acceptance Criteria
1.  When my buddy profile is displayed, I can choose to delete it by clicking on the "Delete" button.
2.  Only a signed in user and the owner of the particular buddy profile can delete the respective form.
3.  The user is asked to confirm they are sure they want to delete the form in order to avoid accidental deletion.

### Tasks
- [ ]  Create delete view (UpdateView)
- [ ]  Add and connect delete button on the buddy form
- [ ]  Create a 503 - unauthorized access page in case someone else than the owner wants to delete the buddy profile
- [ ]  Make sure the user is signed in and the owner of the buddy profile (LoginMixin and UserPassesTestMixin)
