### ISSUE TITLE
User Story # 8 - Delete User Profile (Contact Info)

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#26]
As a ** registered user** I can **press delete button on my user profile/contact form** so that I can **delete all provided information regarding my contact details**

### Acceptance Criteria
1.  When my user profile/contact info is displayed, I can choose to delete it by clicking on the "Delete" button.
2.  Only a signed in user and the owner of the particular profile can delete the respective form.
3.  The user is asked to confirm they are sure they want to delete the form in order to avoid accidental deletion.

### Tasks
- [x]  Create delete view (UpdateView)
- [x]  Add and connect delete button on the contact detail form
- [x]  Create a 503 - unauthorized access page in case someone else than the owner wants to delete the user profile
- [x]  Make sure the user is signed in and the owner of the user profile (LoginMixin and UserPassesTestMixin)
