### ISSUE TITLE
User Story #14 - Create Booking

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#28]
As a **user** I can **reserve a court** so that I can **play at a time that suits me and can avoid come to a full club.**

### Acceptance Criteria
1.  User can choose date, time, court and their opponents.
2.  User can make maximum one reservation per day.
3.  Reservation for a court+time+date must be unique to avoid overbooking.
4.  User can specify 1 opponent for singles.
5.  User can specify 3 opponents for doubles.

### Tasks
- [ ] Create a new booking app and connect urls
- [ ] Create Booking view
- [ ] Restrict 1 booking per day per user, maximum 1 hour
- [ ] Allow user to choose 1 opponent
- [ ] Allow user to choose 3 opponents
- [ ] Make combination of date+time+court unique to avoid overbooking.
- [ ] Only a signed in user may create a booking.
- [ ] Only a user who has filled in his contact details can make a booking.

**Comment by lucia2007** [comment]
I am not restricting the number of courts per user per day at the moment as it is not necessary. It's a won't have.
