### ISSUE TITLE
User Story #15 - View All Bookings (ListView)

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#29]
As a **signed in user/staff member** I can **view all the bookings** so that I can **see when other people are playing/the courts are busy**

### Acceptance Criteria
1.  Signed in user/staff member can access the Bookings view through the navbar (at the moment link named Staff)
2.  The booking page show all the bookings with their details (owner, opponents, day, time, court)

### Tasks
- [x]  Create Bookings template page
- [x]  Connect views and urls
- [x]  Update navbar links to take the user to the Bookings page
- [x]  Give basic styling to the page
