### ISSUE TITLE
Dev Task #5 -Deployment

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#3]
As a  **developer**, I can **do the necessary steps in Django/app** so that **the project can be deployed successfully**

### Acceptance Criteria:
1.  Django can see where the templates are stored.
2.  Django can see where the project is hosted.
3.  Successful first deployment.

### Tasks:
- [x]  Set up the templates directory in settings.py
- [x]  Add the Heroku host name into ALLOWED_HOSTS in settings.py
- [x]  Create the media, static and templates directories
- [x]  Create a Profile
- [x]  Save, add, commit, push
- [x]  Deploy
