### ISSUE TITLE
User Story #16 Booking Delete View

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#30]
As a ** registered user/superuser** I can **press delete button on my booking details** so that I can **delete my/any user's booking**

### Acceptance Criteria
1.  When my list of bookings is displayed, I can choose to delete any of the bookings by clicking on the "Delete" button.
2.  Only a signed in user and the owner of the particular booking or the superuser can delete the respective reservation.
3.  The user/superuser is asked to confirm they are sure they want to delete the reservation in order to avoid accidental deletion.

### Tasks
- [x]  Create delete view (UpdateView)
- [x]  Add and connect delete button on the booking detail form
- [x]  Create a 403 - unauthorized access page in case someone else than the owner/superuser wants to delete the buddy profile
- [x]  Make sure the user is signed in and the owner of the booking (LoginMixin and UserPassesTestMixin) or superuser
