### ISSUE TITLE
User Story #17 Edit Booking View

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#31]
As a **user**, I can **edit my bookings** to **update my preferences regarding the day/time/court/opponents**.

### Acceptance Criteria
1.  User is taken to Booking Edit Form when 'Edit' button is clicked
2.  User can see the prefilled fields with their original information which can be edited
3.  The placeholder text disappears when the user starts editing.
4.  New details are saved in the database.

### Tasks
- [x] Edit button takes the user to the booking edit page
- [x] Form with editable fields is displayed
- [x] 'Save' button pushes the changes in the database
