### ISSUE TITLE
User Story #18 Alternate ListView depending on current user (staff, owner)

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#32]
As a **user/staff** I can **see the list of all bookings (staff)/my own bookings (current user)** so that I can **be reminded of my reservations, but also to be able to update them or delete them.***

### Acceptance Criteria
1.  All users can see a list of bookings without delete/update buttons
2.  When a member of staff is logged in, they can see all the bookings made by all the user with the update/delete buttons
3.  When a user is signed in, they can see a list of their own bookings under the Profile Icon.
4.  The user can update or delete their own bookings.

### Tasks
- [x]  Create a list view for bookings
- [x]  Alternate between 'bookings/list/all' or 'bookings/list/own', depending on the url where the request came from (if booking dashboard, show 'all'; if bookings under Profile icon, show only the current user's bookings
- [x]  Restrict the delete/update buttons in the dashboard only for the admin/staff to see
- [x]  The current user should have delete/update buttons available on his own bookings
- [x]  If the user has no bookings, inform the user about that
