### ISSUE TITLE
User Story #13 - View Buddies (ListView)

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#33]
As a **user** I can **visit the Find Your Perfect Buddy page** so that I can **find the perfect match for my tennis practice**

### Acceptance Criteria
1.  User can access the list of Buddies with their details when clicking on "Find The Perfect Buddy" tab in navlink
2.  The page displays all buddies but the current user's

### Tasks
- [x]  Create Buddies template page
- [x]  Connect views and urls
- [x]  Update navbar links to take the user to Buddies page 
- [x]  Use bootstrap cards to display buddies
