### ISSUE TITLE
User Story #18 Basic search functionality

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#36]
As a **signed in user** I can **search among the buddies** so that I can **find the best partnert to play with**

### Acceptance Criteria
1.  Search window and a search button appear in the NavBar when the user is on "Find the Perfect Buddy" page
2.  The user can search for different levels, practice type, game type and availability.

### Tasks
- [x]  Add a search window and search button to the navbar
- [x]  Make it appear only on a Find the Perfect Buddy page
- [x]  Import Q from django.db.models
- [x]  Create get_queryset(self, **kwargs) function following this tutorial: (https://www.youtube.com/watch?v=w4ilq6Zk-08&list=PLCC34OHNcOtrZnQI6ZLvGPUWfQ6oh-D6H&index=7&t=2s)
- [x]  Enable searching for game_type, availability, practice_type, gender and level
- [ ]  The user should be offered values to search for in the form ("beginner", "doubles", "morning")

**Comment by lucia2007** [comment]
For now, I am not adding a modal with values that can be searched for. It is a could-have.
