### ISSUE TITLE
User Story #21 - Improve website's style

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#38]
As a **user** I can **enjoy browsing the webpage while looking for information** so that **I don't feel compelled to leave**

### Acceptance Criteria
1.  All main elements are correctly aligned, with margins and paddings
2.  There is an overlay on the carousel images so that the text is more legible
3.  Tables and forms should have basic styling

### Tasks
- [x]  Fix margins/padding/flex-direction of the navbar elements when approached from the hamburger
- [x]  Add an overlay over the carousel images, so that the text is easily legible
- [x]  Keep the original Bootstrap fonts as they work well with the theme
- [x]  Add basic styling to tables/forms
