### ISSUE TITLE
Dev Task #6 - Set up Django allauth

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#4]
As a **developer**, I can **install and set up Django allauth** so that **the users can be authenticated**

### Acceptance Criteria:
1.  Successful installation of Django allauth
2.  Successful implementation of allauth prerequesites in urls.py and settings.py

### Tasks:
- [x]  Install allauth
- [x]  Update Templates in settings.py to include context_processors.request for HTTP request access
- [x]  Add AUTHENTICATION_BACKENDS in settings.py to enable user email login
- [x]  Include django.contrib.sites, allauth, allauth.account, allauth.socialaccount into INSTALLED_APPS
- [x] Set SITE_ID=1 under AUTHENTICATION_BACKENDS in case you will be implementing logging in with social media 
- [x] Add allauth accounts url path to project level urls.py
- [x] Migrate new apps
