### ISSUE TITLE
User Story #22 Make a more sophisticated visual booking system

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#40]
As a **user** I can **easily see which courts are available for booking in a calendar** so that I **don't have to randomly look for free date/time/court combinations**.

### Acceptance Criteria
1.  The Booking link in NavBar takes the user to a table where each cell for the chosen date indicates if the court is free or booked.
2.  If court is free, the user can click on the hyperlink which carries the information about the chosen date, time and court and is taken to the AddBooking form, where they just need to specify the opponents as all the other information is already prefilled.
3.  The user is warned if they are making a booking in the past, but this behaviour is allowed because sometimes it's necessary to put in the booking retrospectively for insurance reasons.

### Tasks
- [x]  Create a table using django-tables2 (install and freeze requirements)
- [x]  Populate the table with information if the court is free or booked
- [x]  Make the "Book now" message into a hyperflink which takes the user to the AddBooking form
- [x]  Allow bookings in the past, with a warning, for insurance purposes
- [x]  Make the bookings in the table respond to the date chosen in datepicker form.
- [x]  Prefill the AddBooking form (date, time, court) with query_params which are a part of the url.
