### ISSUE TITLE
User Story #24 Booking Calendar

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#42]
As a **signed in user** I can **easily see which courts are free on a given day** so that I **don't have to keep guessing a combination of court/time/date which would be free**.

### Acceptance Criteria
1.  When the user clicks on Booking in NavBar they are taken to a 'bookingcalendar' page where they see which courts are free and which are booked.
2.  The user can choose a date on which they want to make a booking in the datepicker.
3.  The user can make a booking in the past as well for insurance purposes, but is warned about this fact.
4.  When the user clicks on a "Book now" button, they are taken to 'AddBooking' form, where the date/time/court is prefilled according to the cell on which they had clicked.

### Tasks
- [x]  Create a booking calendar table, using django-tables2 (install and add to requirements)
- [x]  Fill in the cells with information about booked/free (book now) based on the data from the database.
- [x]  If free, make "Book now" into a clickable link which takes the user to the AddBooking form.
- [x]  Change the urls, so that when user clicks on Booking in NavBar, they are taken to the 'bookingcalendar'.
- [x]  Add a date picker to the 'calendar.html' and make it possible to dynamically change the content of the table based on the chosen date.
- [x]  Allow bookings in the past, as sometimes the bookings need to be added in retrospectively, if someone had forgotten to do it.
- [x]  Show a warning if the user if the user is making a booking in the past.
