### ISSUE TITLE
User Story #25  Add carousel

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#43]
As a **user** I can **be visually attracted to the app and see the main site features on the moving carousel** so that I can **quickly get an idea what the app offers**

### Acceptance Criteria
1.  Create a visually pleasing carousel with three main images/features (Itroduction, Find a buddy, Book a court)
2.  User can click on the most used links on the carousel images (singup, login, book,...)
3.  The carousel is moving so the information is varied
4.  There is an overlay on the carousel images for better legibility

### Tasks
- [x]  Import a bootstrap carousel with auto-play
- [x]  Change images to correspond to the theme of the app
- [x]  Add brief description of each feature.
- [x]  Add hyperlinks and buttons to take the user to the desired parts of the app.
- [x]  Add an overlay layers so the text is more easily legible.
