### ISSUE TITLE
User Story #26 Display messages upon user actions

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#44]
As a **user I want to be informed about different user actions** so that I can **be sure that the itended action took place**.

### Acceptance Criteria
1.  User is informed about sing up, sing in and sing out.
2.  User is informed about creation, update or deletion of their Contact details.
3.  User is informed about creation, update or deletion of their Buddy details.
4.  User is informed about creation, update or deletion of their Bookings.
5.  User is warned when they have made a booking in the past.

### Tasks
- [x]  Add messages to all CRUD steps for allauth actions.
- [x]  Add messages to all CRUD steps for Contact details.
- [x]  Add messages to all CRUD steps for Buddy details.
- [x]  Add messages to all CRUD steps for Booking details including a warning about making a booking in the past.
