### ISSUE TITLE
User Story #24 Add Cancel button for all edit and delete forms

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#45]
As a **user** I want to **press a cancel button which will take me to the previous page** so that I **don't have to use the Back button**

### Acceptance Criteria
1.  Add Cancel button to the edit forms for Profile, Buddy and Booking
2.  Add Cancel button to the delete forms for Profile, Buddy and Booking
3.  The cancel button takes the user to their profile detail, buddy detail or back to their own bookings.

### Tasks
- [x]  Add Cancel button to edit form for Profile/Contact info (take user back to their Contact details)
- [x]  Add Cancel button to edit form for Buddy (take user back to their Buddy profile)
- [x]  Add Cancel button to edit form for Booking (take user back to 'bookings/list/own')
- [x]  Add Cancel button to delete form for Profile/Contact info (take user back to their Contact details)
- [x]  Add Cancel button to delete form for Buddy (take user back to their Buddy profile)
- [x]  Add Cancel button to delete form for Booking (take user back to 'bookings/list/own')
