### ISSUE TITLE
Dev Task #4 - Set up Cloudinary

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#5]
As a **developer**, I can **link the project to Cloudinary** so that **I can upload images to a permanent file storage**

### Acceptance Criteria:
1.  Successful connection of Cloudinary to the project
2.  Successful connection of Cloudinary to Heroku
3.  Configuration of Media and static files

### Tasks
- [x] Add Cloudinary API env variable to env.py and Heroku
- [x] Set DISABLE_COLLECTSTATIC on Heroku (REMOVE BEFORE DEPLOYMENT)
- [x] Add Cloudinary libraries to INSTALLED_APPS in setting.py
- [x] Set Cloudinary as storage for media and static files in settings.py
