### ISSUE TITLE
User Story #25 Inform the user when they have made a booking in the past

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#52]
As a **user** I **can clearly see that I made a booking in the past** so that I can **be made aware of the fact**.

### Acceptance criteria
1.  The user is informed about having created a booking successfully, the message disappears after a short time.
2.  The user is informed about having made a booking in the past. A warning message appears, which has to be dismissed by a click on "x".

### Tasks
- [x]  Write a function which checks if the booking was made on a date in the past.
- [x]  Write a function which checks if the booking was made on the current day, but the selected hour has already passed.
- [x]  Add a warning message to this action.
