### ISSUE TITLE
Dev Task #13 Do thorough testing of all aspects of the application to make sure everything works seamlessly and write up the documentation

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#54]
As a **developer** I can **do thorough manual internal and external testing** so that I can **be sure that my application is running seamlessly**.

### Acceptance Criteria
1.  No major errors left in code
2.  Any existing errors are documented
3.  HTML is error free
4.  Python files are error free
5.  JS files are error free
6.  Browser compatibility confirmed
7.  Responsivness tested
8. Lighthouse results are in the recommended range
9.  User stories tested
10.  Manual testing conducted
11.  All above mentioned sections are thoroughly documented in the testing.md file.
 
### Tasks- [x]  Validate HTML of all pages
- [x]  Run LightHouse tests
- [x]  Testing.md Lighthouse section
- [x]  HTML Validation
- [x]  Testing.md HTML validation section
- [x]  Validate all python files with PythonLinter
- [x]  Testing.md Python validation section
- [x]  Validate JS code
- [x]  Testing.md JS validation section
- [x]  Check browser compatibility
- [x]  Testing.md Browser compatibility section
- [x]  Check site responsiveness
- [x]  Testing.md Responsiveness section
- [x]  Testing.md User Stories testing section
- [x]  Testing.md Manual testing section
- [x]  Check error Pages (404, 403, 500)
