### ISSUE TITLE
User Story #27 Phone number validation

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#57]
As a **site owner** I want **the user to provide their phone number in valid format** so that I can **contact them if necessary**

### Acceptance Criteria
1.  User has to enter the phone number in a given format (+353xxxxxxxxx)
2.  The user is informed if the phone number is not valid.
3.  The user sees a prompt of how the phone number should look.

Tasks:
- [x]  Incorporate a regex validator for phone number in the desired format
- [x]  Display a warning if phone number is invalid
- [x]  Give a prompt to the user to know what format is expected
- [x]  Update Readme
