### ISSUE TITLE
User Story #29 Add validators for user inputs

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#58]
As a **site owner** I can **make sure that the user enters valid information** so that **they can be contacted in time of need**.

### Acceptance Criteria
1.  Input is validated for first name, last name and email on Contact us form.
2.  Input is validated for first name, last name and phone number for Contact Info (User profile).
3.  The user is informed if wrong information is entered and the form does not save.
4.  The user sees a suggestion as to how to correct the inputs.

### Tasks
- [x] Create regex validators for first name, last name and phone number.
- [x] Apply them to form fields in relevant forms.py.
- [x] Display error messages to user.
