### ISSUE TITLE
Dev task #12 Technologies and packages used, Testing, ERD, Credits, Error Pages

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#59]
As a **developer** I can **document technologies, testing, ERD, credits, Error pages sections thoroughly** so that I can **refer to the used technologies, tutorials etc. in the future and to avoid plagiarism**

### Acceptance Criteria
1.  Technologies sections well documented 
2.  Testing section explained
3.  ERD schema explained
4.  Credits documented
5.  Error pages described

### Tasks
- [x]  Write down all technologies used with a brief description
- [x]  Shortly explain how testing was done (details in testing.md file)
- [x]  Add ERD schema images and a brief description of models.
- [x]  Document all tutorials and links which were used in the development process.
- [x]  403, 404, 500 error pages - pictures and case description
