### ISSUE TITLE
Dev Task #3 - Set up Heroku

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#6]
As a **developer**, I can **set the project to use an external database** so that **my app can be deployed successfully**

### Acceptance Criteria:
1.  Successful creation of the Heroku app
2.  Successful creation of the new postrgreSQL database instance
3.  Successful connection of the database to the workspace and Heroku

### Tasks:
- [x]  Create a new Heroku app
- [x] Create a database instance in ElephantSQL
- [x] Create the env.py file and add to .gitignore
- [x] Update settings.py to take env.py into account and hook up the db
- [x] SECRET_KEY
- [x] Migrate the db structure
- [x] Add config vars to Heroku - DATABASE_URL
