### ISSUE TITLE
Dev task #14 Readme Deployment

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#60]
As a **developer ** I can **minutely describe the deployment process** so that I can **easily replicate it for future projects**

### Acceptance criteria
1.  Clear instructions including pictures for GitHub project creation
2.  Clear instructions including pictures for ElephantSQL db creation
3.  Clear instructions including pictures for Cloudinary set up
4.  Clear instructions including pictures for deployment to Heroku

### Tasks
- [x]  Take screenshots and describe GitHub project creation
- [x]  Take screenshots and describe deployment to Heroku
- [x]  Describe ElephantSQL db setup
- [x]  Describe Cloudinary setup
