### ISSUE TITLE
Dev Task #2 - Create Django Project

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/tennis_buddies#7]
As a **developer**, I can **create the Django project and app** so that **I can set up the database**

### Acceptance Criteria:
1.  Create a directory for the Django project
2.  Create the TennisBuddies app

### Tasks
- [x]  Create the Django project TennisBuddies
- [x] Create the TennisBuddies app (buddy)
- [x] Add the buddy app to the INSTALLED_APPS in settings.py
- [x] Migrate the changes to the database
- [x] Add 8000 port url to ALLOWED_HOSTS
- [x] Run server to check if all is working
